---
title: "Feb 18 Notes"
author: "Hannah Xiao Si Laws"
date: "2/18/2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#functions
?coef
?summary
?lm
?resid
?predict
car::scatterplotMatrix
?solve
car::residualPlots
?poly
#variable selection
?add1
?drop1
?step
#or
?stepAIC

#%*% is matrix multiplication
?t
?zapsmall
?anova
?update

pf(4,3,10, lower = FALSE)
pf(3.47,2,16, lower = FALSE)#using 5% conf interval, we'd fail to reject Ho.


```



```{r}
site <- "http://www-bcf.usc.edu/~gareth/ISL/Advertising.csv"
AD <- read.csv(site)

#~. is like a bookmark for functions
```

```{r}
Credit <- read.csv("http://www-bcf.usc.edu/~gareth/ISL/Credit.csv")

#women carry less on credit balance than men, but women have lower credit score than men
#trad. men income>women income. therefore, men can spend more, can also have more on credit balance. women spend more of total income, therefroe credit score lower.
names(Credit)
plot(Balance~Gender,data = Credit)

mean(Credit$Balance[Credit$Gender == " Male"])
mean(Credit$Balance[Credit$Gender == "Female"])
#or
tapply(Credit$Balance, Credit$Gender, mean)

mod <- lm(Balance~Gender, data = Credit)
summary(mod)



```











